name: sincfold
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch=2.1
  - pandas=2.0.2
  - numpy=1.24.2
  - scikit-learn=1.2.1
  - tqdm=4.64.1
  - pillow
  - pip:
    - grakel==0.1.10
